### ISSUE TITLE
bug ở mục favorite

### ISSUE THREAD

**Issue by malderfox30** [leduc-debug/YourCinemaCritics#13]
lưu favorite list là riêng từng user chứ sao đăng nhập vào nhiều tài khoản khác nhau lại cùng 1 favorite list vậy?

**Comment by leduc-debug** [comment]
thì tau nói để tau sửa rồi mà..... Thêm 1 dòng thôi
tại hắn chưa lấy lại dữ liệu nơi firebase
nếu mi thoát app rồi bật lại thì chạy như bth

**Comment by malderfox30** [comment]
fixed
